### ISSUE TITLE
Powerschool license warning

### ISSUE THREAD

**Issue by ki7qfv** [ajmwagar/powerschool_gradecheck#7]
Using this app may be a violation of your powerschool license agreement, and could get you in legal hot water with them:

https://www.powerschool.com/terms/

Prohibited Actions
By your use of the Site, you agree that you will NOT: reverse engineer, duplicate, publish, modify, extract data using automated processes such as bots and webcrawlers (scraping), or otherwise distribute the materials on this Site unless specifically authorized in writing by PowerSchool to do so.

**Comment by ajmwagar** [comment]
Hey April,

Thanks for the note. It's good to hear from you.

I agree that use of this app may now pose issues for current users of Powerschool. I graduated from SPS in 2021, so I haven't been a user for a long time. I plan on leaving this up for educational purposes, and also because it's a fun memory.

Perhaps I'll add a similar disclaimer to the README.md.

Thanks again.

Best,

Avery

**Comment by ki7qfv** [comment]
you may get a cease-and-desist legal warning from powerschool soon.
They're on the prowl.

One of the app clones of the source app decided to sell/monetize and
created a firestorm.
